# Generated by Django 5.0.4 on 2024-04-25 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_schedule', '0004_session_trainer'),
        ('gymApp', '0003_alter_profile_qr_code'),
        ('gym_info', '0002_contactinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='remaining_personal_trainings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='included_personal_trainings',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PersonalTrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.IntegerField(default=60)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymApp.membership')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='class_schedule.session')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym_info.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedTrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.IntegerField(default=60)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='class_schedule.session')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym_info.trainer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
