# Generated by Django 5.0.4 on 2024-04-30 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0004_membership_remaining_personal_trainings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiptype',
            name='price_yen',
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='price_yen_female',
            field=models.DecimalField(decimal_places=2, default=4000, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='price_yen_male',
            field=models.DecimalField(decimal_places=2, default=4000, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.CreateModel(
            name='TrialPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
                ('credited', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
