# Generated by Django 5.0.4 on 2024-05-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0006_profile_qr_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='stripe_price_id_female',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='stripe_price_id_male',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
