# Generated by Django 5.0.4 on 2024-05-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0007_membershiptype_stripe_price_id_female_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trialpayment',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
