# Generated by Django 5.0.4 on 2024-05-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0008_membership_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymvisit',
            name='session_type',
            field=models.CharField(choices=[('regular', 'Regular Session'), ('personal_training', 'Personal Training Session')], default='regular', max_length=20),
        ),
    ]
