# Generated by Django 5.0.4 on 2024-05-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0010_alter_membership_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
