# Generated by Django 5.0.4 on 2024-05-11 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0011_alter_membership_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialpayment',
            name='credited_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
