# Generated by Django 5.0.4 on 2024-05-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0012_trialpayment_credited_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trialpayment',
            old_name='credited',
            new_name='discount_credited',
        ),
        migrations.RenameField(
            model_name='trialpayment',
            old_name='credited_on',
            new_name='used_on',
        ),
    ]
