# Generated by Django 5.0.4 on 2024-05-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0013_rename_credited_trialpayment_discount_credited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialpayment',
            name='used_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
