# Generated by Django 5.0.4 on 2024-05-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0014_alter_trialpayment_used_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='membership_types/'),
        ),
    ]
