# Generated by Django 5.0.4 on 2024-05-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0017_alter_membership_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
