# Generated by Django 5.0.4 on 2024-05-23 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0018_stripeevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceholderMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('initial_price_yen', models.DecimalField(decimal_places=2, max_digits=8)),
                ('remaining_sessions', models.IntegerField(default=0)),
                ('remaining_personal_trainings', models.IntegerField(default=0)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('base_membership_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholder_for', to='gymApp.membershiptype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placeholder_membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
