# Generated by Django 5.0.4 on 2024-05-24 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0019_placeholdermembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeholdermembership',
            name='base_membership_type',
        ),
        migrations.RemoveField(
            model_name='placeholdermembership',
            name='user',
        ),
        migrations.DeleteModel(
            name='StripeEvent',
        ),
        migrations.DeleteModel(
            name='PlaceholderMembership',
        ),
    ]
