# Generated by Django 5.0.4 on 2024-05-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_info', '0002_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='bio_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='name_ja',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
