# Generated by Django 5.0.4 on 2024-06-13 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_info', '0004_trainer_contact_info_trainer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='contact_info',
        ),
    ]
