# Generated by Django 5.0.4 on 2024-04-19 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_schedule', '0002_remove_booking_scheduled_class_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='class_schedule.session'),
        ),
    ]
