# Generated by Django 5.0.4 on 2024-04-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_schedule', '0004_session_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='Recur until this date, weekly.', null=True),
        ),
    ]
