# Generated by Django 5.0.4 on 2024-05-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_schedule', '0005_session_recurrence_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='description_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='title_ja',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
