# Generated by Django 5.0.4 on 2024-05-11 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_usd',
            new_name='price',
        ),
    ]
